import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const score: number = 0
  return (
    <div className={styles.container}>
      <Head>
        <title>CV Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to our CV Scanner</h1>
        <p>Please upload your CV here:</p>
        <input type='file'></input>
        <p>Please enter the keywords you are looking for:</p>
        <form>
          <div className="keyword">
          <label>Keyword 1</label>
          <input type="text" id='keyword1' name='keyword1'/>
          <label>Score</label>
          <select>
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            </select>
            </div>
            <div className="keyword">
          <label>Keyword 2</label>
          <input type="text" id='keyword2' name='keyword2'/>
          <label>Score</label>
          <select>
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            </select>
            </div>
            <div className="keyword">
          <label>Keyword 3</label>
          <input type="text" id='keyword3' name='keyword3'/>
          <label>Score</label>
          <select>
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            </select>
            </div>
        </form>
        <button>Calculate score</button>
        <h2>This CV scores {score} points</h2>

      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
